### PR TITLE
Fix for Python 3

### PR DESCRIPTION
**Pull request by Woolworths**
Otherwise it doesn't work..

### CODE REVIEW

**Comment by Woolworths** [comment]
Check out my branch -- Python3 is fully working along with Python2. Because I changed the folder structure, you would want to update the `setup.py` if you were to push it.

**Comment by Woolworths** [comment]
My version is now FULLY WORKING AND TESTED for Python2 and Python3. However, to commit this, you need to change the setup.py accordingly, and change the Python3APIImpl to:
- import six
- change next() -> six.next()
- change *.iteritems -> six.iteritems(*)
For the __init__.py I changed urllib to requests as it works better for Python2 + Python3 and it looks cleaner.  
To run, read the README.md (pull, run and inspect) then get the IpAddress variable given back and use that as a proxy. Enjoy!

**Comment by psiinon** [comment]
Are you going to submit a new PR for this?
Cheers

**Comment by Woolworths** [comment]
I did submit a PR, but decided that it would be best left to the ZAP guys to finish it off. I submitted my PR so you guys could get ideas for how I managed to have compatibility with Python2 + Python3 (again, this works for both). This works as a library for me, however there are things that need to be changed (such as the `setup.py` variables and the Python3APIImpl). If you would like though, I could submit it.

**Comment by psiinon** [comment]
Please do - I wrote the original python API, but I'm not a python programmer. But I can definitely test and comment on a PR, and we can then merge it when its ready :)

**Comment by thc202** [comment]
@Woolworths did you take a look at #1 (and #2)? Could check/review/comment about the proposed change(s)?
(Both pull requests seem to provide support for Python 3.)

**Comment by Woolworths** [comment]
@thc202 Just checked it out and I will write my review of it on his PR.

**Comment by wdhongtw** [comment]
Hi @psiinon ! Would you test and merge this PR in the future?

I would like to use this API in Python 3 environment. It will be fantastic if this official API package works without patch. :D

**Comment by ravenium** [comment]
Has anyone taken a shot at reconciling the conflicts and "three-proofing" this? It seems the codebase has been updated to support new API functionality and the patch is out of date now.

**Comment by thc202** [comment]
I don't think so, but we can't resolve the conflicts in this branch though. @Woolworths could you give permission [1] so that we can fix the conflicts?

[1] https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by Woolworths** [comment]
@thc202 Sure! I will come back to this shortly and ensure that it is working with the master branch. Correct me if I'm wrong but this project is automatically generated from the Python3APIImpl class? If so changes would need to be made to that class as mentioned in my second comment. It has been a while since I have looked through the source code, my apologies.

**Comment by thc202** [comment]
Great, thank you! OK, I'll take a look at the generator to ensure it produces the new/expected code (when ready I'll open a pull request linking to this one).

**Comment by thc202** [comment]
Conflicts resolved, not ready to merge though.

**Comment by thc202** [comment]
Ready for review/merge. Tested with Python 2.7 and 3.4, installed and run fine in both cases. Feedback appreciated...

(Reverted the package and class rename, to allow to keep using the same code.)

**Comment by psiinon** [comment]
@Woolworths Many thanks for doing this - how would you like to be credited? 
https://github.com/zaproxy/zap-core-help/wiki/HelpCredits

**Comment by Woolworths** [comment]
@psiinon No problem! I guess the most suitable would be my name: "Jean Abed"!

**Comment by thc202** [comment]
Done in zaproxy/zap-core-help#103. Thank you!

**Pull request merged**
