### PR TITLE
Updated for 2.11.1

### PR DESCRIPTION
**Pull request by psiinon**
And the latest add-ons.
Also updated the README with details of how to do this in the future.

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by psiinon** [comment]
Strange - the oast.py file did not have any methods.
I've removed it to fix the build, but we should probably onvestigate why the OAST API calls were not present...

**Review by kingthorin — COMMENTED** [review]
With the exception of the whitespace blocks this seems fine to me. (Also assuming tests pass :wink:)

**Comment by psiinon** [comment]
Yeah, those dont look ideal but will require java changes. For not I think its ok to include them?

**Comment by kingthorin** [comment]
Sure

**Review by kingthorin — APPROVED** [review]

**Review by thc202 — APPROVED** [review]

**Pull request merged**
