### PR TITLE
Copied code from zaproxy

### PR DESCRIPTION
**Pull request by psiinon**

### CODE REVIEW

**Comment by kingthorin** [comment]
Looks good to me. 

Being completely truthful, I only skimmed it. Assuming it's a straight copy.

**Comment by psiinon** [comment]
Yeah, it was a straight copy. But @thc202 still spotted some issues with the example code, so I'll update that :)

**Comment by kingthorin** [comment]
Ok

**Comment by psiinon** [comment]
Updated the example and regenerated the docs

**Comment by thc202** [comment]
Looks good to me.

**Pull request merged**
