### PR TITLE
Add soap API

### PR DESCRIPTION
**Pull request by thc202**
Add the API of SOAP Scanner add-on (version 3).

### CODE REVIEW

**Comment by psiinon** [comment]
Looks ok but pylama failing?

**Comment by thc202** [comment]
Fixed in #36, it's unrelated to these changes (I'll rebase once the other is merged).

**Comment by Kilo59** [comment]
What's the hold-up?
@thc202 Can you just add the changes from #36 to this PR? I realize it's unrelated but It's a very minor change.

**Comment by thc202** [comment]
We usually merge after two reviews.

**Comment by thc202** [comment]
Rebased, build passing.

**Comment by psiinon** [comment]
@kingthorin review? :)

**Comment by Kilo59** [comment]
Do you guys want some help setting up an automatic deploy to pypi when master is updated?

**Pull request merged**
