### PR TITLE
Updated to supply apikey on all reqs and for 2.6.0

### PR DESCRIPTION
**Pull request by psiinon**

### CODE REVIEW

**Comment by psiinon** [comment]
Ah, I've found another problem with this. It fails with certificate errors when proxying to http sites. I'll need to fix that :/

**Comment by psiinon** [comment]
I think the codes ok now, but the tests are failing :( @jotes - any suggestions?

**Comment by kingthorin** [comment]
Build failure: https://travis-ci.org/zaproxy/zap-api-python/builds/213395990#L240-L244

**Comment by jotes** [comment]
Hey, I'll look into it today after may daywork if you won't mind - I'll post the PR to your branch.

**Comment by psiinon** [comment]
@jotes - that wound be great :)

**Comment by psiinon** [comment]
@jotes I've incorporated the changes you made that I could get to work, but not the ones I couldnt ;)
Pretty sure the tests will fail again ... and they have :P

**Comment by psiinon** [comment]
Thanks @jotes - that did the trick!

**Comment by psiinon** [comment]
@kingthorin this ok (not sure if you watch this repo;)

**Comment by kingthorin** [comment]
Ya, are we squashing via github or are you gonna "fix-up"?

**Comment by thc202** [comment]
That's a good question, it contains commits from @jotes too.

**Comment by psiinon** [comment]
Hopefully fixed the commits now

**Pull request merged**
